"""callforward table

Revision ID: e7fe08c63334
Revises: 
Create Date: 2021-02-07 15:16:23.669858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fe08c63334'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callforward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exten', sa.String(length=4), nullable=True),
    sa.Column('forward_phone', sa.String(length=11), nullable=True),
    sa.Column('timeout', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callforward_exten'), 'callforward', ['exten'], unique=True)
    op.create_index(op.f('ix_callforward_forward_phone'), 'callforward', ['forward_phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_callforward_forward_phone'), table_name='callforward')
    op.drop_index(op.f('ix_callforward_exten'), table_name='callforward')
    op.drop_table('callforward')
    # ### end Alembic commands ###
